package pojo;
// Generated Sep 20, 2024 9:19:41 AM by Hibernate Tools 4.3.1


import DAO.DAOConcert;
import java.util.Date;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Concert generated by hbm2java
 */
@Entity
@Table(name = "concert")
public class Concert  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
     private Integer id;
     
    private String name;
     private String desc;
     private int quantity;
     private int price;
     private Date dateOfConcert;
     
     private int trailerId;
     private int viewConcertId;
     private Date createdAt;
     private Date updatedAt;

     @ManyToOne(fetch = FetchType.EAGER)
     @JoinColumn(name = "viewConcertId", referencedColumnName = "id", insertable = false, updatable = false)
     private ConcertView concertView;

     @ManyToOne(fetch = FetchType.EAGER)
     @JoinColumn(name = "trailerId", referencedColumnName = "id", insertable = false, updatable = false)
     private ConcertTrailer concertTrailer;
     
    public Concert() {
    }

    public Concert(String name, String desc, int quantity, int price, Date dateOfConcert, int viewConcertId, int trailerId, Date createdAt, Date updatedAt, ConcertView concertView, ConcertTrailer concertTrailer) {
        this.name = name;
        this.desc = desc;
        this.quantity = quantity;
        this.price = price;
        this.dateOfConcert = dateOfConcert;
        this.viewConcertId = viewConcertId;
        this.trailerId = trailerId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.concertView = concertView;
        this.concertTrailer = concertTrailer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public Date getDateOfConcert() {
        return this.dateOfConcert;
    }
    
    public void setDateOfConcert(Date dateOfConcert) {
        this.dateOfConcert = dateOfConcert;
    }
    public int getViewConcertId() {
        return this.viewConcertId;
    }
    
    public void setViewConcertId(int viewConcertId) {
        this.viewConcertId = viewConcertId;
    }
    public int getTrailerId() {
        return this.trailerId;
    }
    
    public void setTrailerId(int trailerId) {
        this.trailerId = trailerId;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    
    public ConcertView getConcertView() {
        return concertView;
    }

    public void setConcertView(ConcertView concertView) {
        this.concertView = concertView;
    }
    
    public ConcertTrailer getConcertTrailer() {
        return concertTrailer;
    }

    public void setConcertTrailer(ConcertTrailer concertTrailer) {
        this.concertTrailer = concertTrailer;
    }

//    public List<Concert> getallrecords(){
//        DAOConcert plg = new DAOConcert();
//        List<Concert> lPlg = plg.retrieveTblConcert();
//        return lPlg;
//    }


}


