package pojo;
// Generated Sep 20, 2024 9:19:41 AM by Hibernate Tools 4.3.1


import DAO.DAOConcert;
import DAO.DAOLogin;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;

/**
 * ConcertTicket generated by hbm2java
 */
public class ConcertTicket  implements java.io.Serializable {


     private Integer id;
     private int userId;
     private int concertId;
     private String fullName;
     private String phoneNumber;
     private String idCard;
     private Date createdAt;

    public ConcertTicket() {
    }

    public ConcertTicket(int userId, int concertId, String fullName, String phoneNumber, String idCard, Date createdAt) {
       this.userId = userId;
       this.concertId = concertId;
       this.fullName = fullName;
       this.phoneNumber = phoneNumber;
       this.idCard = idCard;
       this.createdAt = createdAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getConcertId() {
        return this.concertId;
    }
    
    public void setConcertId(int concertId) {
        this.concertId = concertId;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getIdCard() {
        return this.idCard;
    }
    
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public ConcertTicket insert(){
        DAOConcert uDao = new DAOConcert();

        LocalDateTime now = LocalDateTime.now();

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String formattedNow = now.format(formatter);

        this.createdAt = Date.from(now.atZone(ZoneId.systemDefault()).toInstant());

        uDao.insert(this);

        userId = 0;
        concertId = 0;
        fullName = "";
        phoneNumber = null;
        idCard = null;
        
        return this;
    }
    
//    public ConcertTicket getByUserId(){
//        DAOConcert uDao = new DAOConcert();
//        List<ConcertTicket> us = uDao.getBy(userId);
//        if (us != null) {
//            return us.get(0);
//        }
//        return this;
//    }

}


